### ISSUE TITLE
Support more CI systems

### ISSUE THREAD

**Issue by mgedmin** [mgedmin/check-python-versions#9]
This bug is just here to indicate that I'm open to adding support for additional CI systems, especially if people send me pull requests ;)

Things like

- GitLab CI (example: https://gitlab.com/anarcat/undertime/-/blob/master/.gitlab-ci.yml)
- GitHub actions
- CircleCI?
- Azure something-or-other?
- what else is there?

Ideally I'd like several examples to see what the config files look like.

**Comment by mgedmin** [comment]
A bunch of ZopeFoundation repos are getting GitHub actions based on https://github.com/zopefoundation/meta/blob/master/config/default/tests.yml.in:

```yaml
jobs:
  build:
    strategy:
      matrix:
        config:
        # [Python version, tox env]
        - ["3.8",   "lint"]
        - ["2.7",   "py27"]
        - ["3.5",   "py35"]
        - ["3.6",   "py36"]
        - ["3.7",   "py37"]
        - ["3.8",   "py38"]
        - ["3.9",   "py39"]
        - ["pypy2",   "pypy"]
        - ["pypy3",   "pypy3"]
        - ["3.8",   "coverage"]
```
